buttons = [
    [
        InlineKeyboardButton(
text="â•ï¸ Add Me ",
         url="http://t.me/JinWooSungBot?startgroup=new",
        ),
    ],
    [
        InlineKeyboardButton(
            text=" ğŸ¥ Support", url=f"https://t.me/AstorSupport",
        ),
        InlineKeyboardButton(
            text=" ğŸ‰ Updates", url=f"https://t.me/AstorPro",
        ),
        InlineKeyboardButton(
            text=" ğŸ“® Logs", url=f"https://t.me/ErikaLogs"),
    ],
    [
        InlineKeyboardButton(
            text=" ğŸŒ» Chat", url=f"https://t.me/ScoutXLegion",
        ),
        InlineKeyboardButton(
            text=" ğŸ” Help ", callback_data="help_back"),
    ],
  ]
